# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_shad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
