# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_shad', '0002_auto_20170802_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_time',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(verbose_name='Comment text:'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='Comments',
        ),
    ]
