# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_shad', '0003_auto_20170804_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Comment text:')),
                ('comment_autor', models.CharField(max_length=100)),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_shad.Article')),
            ],
            options={
                'db_table': 'Comments1',
            },
        ),
    ]
