# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_shad', '0004_comments1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors_name', models.CharField(max_length=100)),
                ('authors_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_shad.Comments')),
            ],
            options={
                'db_table': 'Authors',
            },
        ),
        migrations.RemoveField(
            model_name='comments1',
            name='comment_article',
        ),
        migrations.DeleteModel(
            name='Comments1',
        ),
    ]
