# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_shad', '0005_auto_20170808_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='authors_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_author',
            field=models.CharField(default='Nemo', max_length=100),
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
